version: "3.8"
services:
  # User Service for testing
  user-service:
    build: ./services/user-service
    ports:
      - "5001:5000"
    environment:
      - DATABASE_URL=postgresql://testuser:testpassword@user_db:5432/testdb
      - SECRET_KEY=mytestsecretkey
    networks:
      - test-network
    command: pytest # Run pytest directly in the user-service container

  # Postgres Database for User Service
  user_db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpassword
      - POSTGRES_DB=testdb
    ports:
      - "5432:5432"
    volumes:
      - user_data:/var/lib/postgresql/data
    networks:
      - test-network

networks:
  test-network:
    driver: bridge

volumes:
  user_data:
