version: "3"

services:
  user-service:
    build: ./services/user-service
    ports:
      - "5001:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://admin:password@db:5432/users_db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
