# version: "3.9"

services:
  user-service:
    build: ./services/user-service
    ports:
      - "5001:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"

volumes:
  postgres_data:
