services:
  user-service:
    build: ./services/user-service
    ports:
      - "5001:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}

  authentication-service:
    build: ./services/authentication-service/
    ports:
      - "5002:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - SMTP_SERVER=${SMTP_SERVER}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
  #
  # product-service:
  #   build: ./services/product-service/
  #   ports:
  #     - "5003:5000"
  #   depends_on:
  #     - db
  #   environment:
  #     - DATABASE_URL=${DATABASE_URL}

  api-gateway:
    build: ./api-gateway/
    ports:
      - "8000:8000"
      - "8443:8443"
    depends_on:
      - user-service
      - authentication-service
    volumes:
      - ./api-gateway/kong.yml:/app/kong.yml

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV}

volumes:
  postgres_data:
